services:
  qdrant:
    image: 'qdrant/qdrant:latest'
    ports:
      - '6333:6333'
      - '6334:6334'

volumes:
  chroma-data:
    driver: local
  grafana-storage: {}

networks:
  net:
    driver: bridge

