### Set the resource path for the file to be processed
### e.g., app.resource=file:///Users/yourname/Downloads/yourfile.pdf
###    or app.resource=classpath:/data/myfile.pdf
app:
  scan:
    recursive: true
    extensions: pdf,txt,docx
  index:
    batchSize: 50
  resource: file:///Users/sjohnson/shared/data/proposals/seed-proposals

#  resource: https://en.wikipedia.org/wiki/Chess
#  resource: file:///Users/sjohnson/shared/data/proposals/seed-proposals/contract-proposal-1.pdf
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
    vectorstore:
      topk: 2
      qdrant:
        initialize-schema: true

    chat:
      observations:
        include-prompt: true
        include-completion: true
  application:
    name: spring-ai-proposalgen-example
  docker:
    compose:
      stop:
        command: down
        arguments: -v
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus

  ### Set sampling probability to 1.0 to enable tracing
  ### on 100% of requests.
  tracing:
    sampling:
      probability: 1.0
