logging:
  level:
    root: INFO
    #org.springframework.ai: DEBUG
    org.springframework.ai.mcp.client: DEBUG
    #org.springframework.boot.autoconfigure: DEBUG

github-mcp-server-url: http://localhost:8081

app:
  scan:
    recursive: true
    extensions: pdf,txt,docx

  match:
    top-k: 5

  ingest:
    skipResumeIngest: true
    batchSize: 50
    # Must be smaller the maximum tokens for embedding model, larger -> irrelevant content, smaller -> more meaningful content.
    #   Experiment with different values to find the best balance for resume matching.
    overlapSize: 20
    chunkSize: 1000
    resume-resources: file:///Users/sjohnson/shared/data/resumes-m5

#  resource: https://en.wikipedia.org/wiki/Chess
#  resource: file:///Users/sjohnson/shared/data/proposals/seed-proposals/contract-proposal-1.pdf
spring:
  datasource:
      password: secret
      username: myuser
      url: jdbc:postgresql://localhost/mydatabase

  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json

    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
          max-tokens: 4096

      embedding:
        options:
          model: text-embedding-ada-002
          top-k: 3

    vectorstore:
      pgvector:
        #
        # The vector store table will be explicitly truncated if the skipResumeIngest=false; otherwise,
        # the existing table will be reused.
        #
        remove-existing-vector-store-table: false
        initialize-schema: true
        dimensions: 1536
        index-type: HNSW
        distance-type: COSINE_DISTANCE

#      embedding:
#        options:
#          model: nomic-embed-text
#          max-tokens: 4096
#          top-k: 3
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: mervinpraison/llama3.2-3B-instruct:8b
#          temperature: 0.2
#
#    vectorstore:
#      topk: 5
#      pgvector:
#        remove-existing-vector-store-table: true
#        initialize-schema: true
#        dimensions: 768
#        index-type: HNSW
#        distance-type: COSINE_DISTANCE
#
#  user:
#    input: What tools are available?


#      client:
#        enabled: true
#        toolcallback:
#          enabled: true
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
#
##          connections:
##            local-mcp-service:
##                command: /Users/sjohnson/.nvm/versions/node/v18.20.6/bin/node
##                args:
##                  - /Users/sjohnson/mydev/experiments/github-repos-manager-mcp/server.cjs
##                env:
##                  GH_TOKEN: ${GH_TOKEN}
#      chat:
#        client:
#          observations:
#            log-prompt: true
#            log-completion: true
#            include-error-loggin: true
#            log-query-response: true
#
#management:
#  tracing:
#    enabled: false
#    zipkin:
#      enabled: false

  application:
    name: spring-ai-skills-matcher

  docker:
    compose:
      stop:
        command: down
        arguments: -v
      enabled: false

